### ISSUE TITLE
支持超时关闭的ws通道

### ISSUE THREAD

**Issue by is** [zwh8800/tap-over-https#1]
现在通过的代理服务器，WebSocket链接最大链接时长是180s。是不是能提供一个什么措施，提前建立一个备用链接，这样能保证上层数据传输连贯性。

**Comment by zwh8800** [comment]
你遇到的这个问题貌似不太好解决😂，因为服务端每建立一个新链接是会分配一个新ip地址的，倒是可以考虑加一个自动重连的机制，不过因为会换ip还是会有不连贯的情况

**Comment by is** [comment]
😄，我想想也是觉得比较麻烦，我先看看代码吧。
